<?php

namespace MineDoc\HomeBundle\Entity;

use MineDoc\HomeBundle\Entity\Chat;
use Doctrine\ORM\EntityRepository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends EntityRepository
{
    public function getLastMessages($i)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM MineDocHomeBundle:Chat c ORDER BY c.id DESC')
            ->setMaxResults($i)
            ->getResult();
    }

    public function deleteMessage($id)
    {
        $query =  $this->getEntityManager()->createQuery('DELETE FROM MineDocHomeBundle:Chat u WHERE u.id = ?1');
        $query->setParameter(1, $id);
        $query->execute();
    }

    public function getLast()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM MineDocHomeBundle:Chat c ORDER BY c.id DESC')
            ->setMaxResults(1)
            ->getSingleResult();
    }

    public function postMessage($login, $message)
    {
        $entry = new Chat();
        $entry->setLogin($login);
        $entry->setMessage($message);
        $entry->setDate(date_create('now'));
        $em = $this->getEntityManager();
        $em->persist($entry);
        $em->flush();
    }
}
