<?php

namespace MineDoc\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getAvailableItems()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT i FROM MineDocHomeBundle:Item i WHERE i.available=1 ORDER BY i.id DESC')
            ->getResult();
    }
}