<?php

namespace MineDoc\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getLastNews($i) {
        return $this->getEntityManager()
            ->createQuery('SELECT i FROM MineDocHomeBundle:News i ORDER BY i.id DESC')
            ->setMaxResults($i)
            ->getResult();
    }
}